import { NgModule } from '@angular/core';
import {
    MatCardModule,
    MatMenuModule,
    MatListModule,
    MatTabsModule,
    MatTreeModule,
    MatIconModule,
    MatSortModule,
    MatBadgeModule,
    MatChipsModule,
    MatInputModule,
    MatRadioModule,
    MatTableModule,
    MatSelectModule,
    MatSliderModule,
    MatButtonModule,
    MatDialogModule,
    MatTooltipModule,
    MatSidenavModule,
    MatToolbarModule,
    MatDividerModule,
    MatStepperModule,
    MatGridListModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatPaginatorModule,
    MatExpansionModule,
    MatNativeDateModule,
    MatDatepickerModule,
    MatProgressBarModule,
    MatSlideToggleModule,
    MatBottomSheetModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule
} from '@angular/material';

@NgModule({

    imports: [
        MatCardModule,
        MatMenuModule,
        MatListModule,
        MatTabsModule,
        MatTreeModule,
        MatIconModule,
        MatSortModule,
        MatBadgeModule,
        MatChipsModule,
        MatInputModule,
        MatRadioModule,
        MatTableModule,
        MatSelectModule,
        MatSliderModule,
        MatButtonModule,
        MatDialogModule,
        MatTooltipModule,
        MatSidenavModule,
        MatToolbarModule,
        MatDividerModule,
        MatStepperModule,
        MatGridListModule,
        MatSnackBarModule,
        MatCheckboxModule,
        MatFormFieldModule,
        MatPaginatorModule,
        MatExpansionModule,
        MatNativeDateModule,
        MatDatepickerModule,
        MatProgressBarModule,
        MatSlideToggleModule,
        MatBottomSheetModule,
        MatAutocompleteModule,
        MatButtonToggleModule,
        MatProgressSpinnerModule
    ],

    exports: [
        MatCardModule,
        MatMenuModule,
        MatListModule,
        MatTabsModule,
        MatTreeModule,
        MatIconModule,
        MatSortModule,
        MatBadgeModule,
        MatChipsModule,
        MatInputModule,
        MatRadioModule,
        MatTableModule,
        MatSelectModule,
        MatSliderModule,
        MatButtonModule,
        MatDialogModule,
        MatTooltipModule,
        MatSidenavModule,
        MatToolbarModule,
        MatDividerModule,
        MatStepperModule,
        MatGridListModule,
        MatSnackBarModule,
        MatCheckboxModule,
        MatFormFieldModule,
        MatPaginatorModule,
        MatExpansionModule,
        MatNativeDateModule,
        MatDatepickerModule,
        MatProgressBarModule,
        MatSlideToggleModule,
        MatBottomSheetModule,
        MatAutocompleteModule,
        MatButtonToggleModule,
        MatProgressSpinnerModule
    ],
})
export class OwnMaterialModule { }






