import { NgModule } from '@angular/core';
import {
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatBottomSheetModule,
    MatButtonToggleModule,
    MatCardModule,
    MatChipsModule,
    MatCheckboxModule,
    MatDialogModule,
    MatDividerModule,
    MatDatepickerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSortModule,
    MatSelectModule,
    MatSliderModule,
    MatSidenavModule,
    MatStepperModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatTabsModule,
    MatTreeModule,
    MatTableModule,
    MatTooltipModule,
    MatToolbarModule,
} from '@angular/material';

@NgModule({

    imports: [
        MatAutocompleteModule,
        MatBadgeModule,
        MatButtonModule,
        MatBottomSheetModule,
        MatButtonToggleModule,
        MatCardModule,
        MatChipsModule,
        MatCheckboxModule,
        MatDialogModule,
        MatDividerModule,
        MatDatepickerModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatGridListModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatSortModule,
        MatSelectModule,
        MatSliderModule,
        MatSidenavModule,
        MatStepperModule,
        MatSnackBarModule,
        MatSlideToggleModule,
        MatTabsModule,
        MatTreeModule,
        MatTableModule,
        MatTooltipModule,
        MatToolbarModule,
    ],

    exports: [
        MatAutocompleteModule,
        MatBadgeModule,
        MatButtonModule,
        MatBottomSheetModule,
        MatButtonToggleModule,
        MatCardModule,
        MatChipsModule,
        MatCheckboxModule,
        MatDialogModule,
        MatDividerModule,
        MatDatepickerModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatGridListModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatSortModule,
        MatSelectModule,
        MatSliderModule,
        MatSidenavModule,
        MatStepperModule,
        MatSnackBarModule,
        MatSlideToggleModule,
        MatTabsModule,
        MatTreeModule,
        MatTableModule,
        MatTooltipModule,
        MatToolbarModule,
    ],
})
export class OwnMaterialModule { }






